### ISSUE TITLE
Encoding of generated JS files

### ISSUE THREAD

**Issue by migo** [softprops/coffeescripted-sbt#4]
It seems that the generated JS files do not have the same encoding as the coffee files.

For example, my coffee files are UTF-8 encoded. Characters like "ä, ö, ü, ß" are broken in the generated JS files.
You probably have to set the file encoding to UTF-8 explicitly when reading the coffee files and when writing the js files.

I think UTF-8 should be the default encoding, but it could also be made configurable.

**Comment by softprops** [comment]
Thanks for pointing this out @migo. I'll look into it tonight

**Comment by softprops** [comment]
Fixed and published a quick [version](http://implicit.ly/coffeescripted-sbt-015). I hadn't noticed this because I aggressively have my default file.encoding set to utf-8 in my sbt script with `-Dfile.encoding=UTF-8`. I switched to another ran `coffee:clean` then `coffee` and quickly spotted the issue.  The default charset should now be utf-8, but you can override that but setting the `coffee:charset` key. Thanks for pointing this out

**Comment by migo** [comment]
Very cool, thank you!

I've, however, just switched to using coffeescript via node.js, since I noticed that compilation is really very much faster there, probably because of the v8 Javascript engine used there...
